### ISSUE TITLE
Support screen should be updated

### ISSUE THREAD

**Issue by alex-taffe** [Triggertrap/triggertrap-ios#11]
This screen is most likely not relevant anymore because the support infrastructure is gone

**Comment by Ross-Gibson** [comment]
As part of this task we should remove the CTFeedbackViewController, and it's dependencies. We should also clean up the `Info.plist` to remove the requirement for `Privacy - Photo Library Usage Description` that this dependency adds.

**Comment by Ross-Gibson** [comment]
@alex-taffe I'm starting work on this task - as I don't want an influx of support questions sent to the old Triggertrap inbox, now that we're stating to update the project.

P.S. I've configured a [project](https://github.com/Triggertrap/triggertrap-ios/projects/1) so that we can track who's working on what - let me know if you have access.
